# Reproducible analysis script. Run from any working directory; paths resolve from the repository.
options(stringsAsFactors = FALSE)
root <- normalizePath(file.path(getwd()), mustWork = FALSE)
if (basename(root) == "R") root <- dirname(root)
data_dir <- file.path(root, "data"); out_dir <- file.path(root, "outputs"); fig_dir <- file.path(root, "figures")
dir.create(out_dir, showWarnings=FALSE); dir.create(fig_dir, showWarnings=FALSE)
if (!requireNamespace("readxl", quietly=TRUE)) stop("Install readxl")
a <- read.csv(file.path(data_dir,"pre_post_scores_full_50students.csv")); q <- read.csv(file.path(data_dir,"questionnaire_post_intervention_corrected.csv"))
stopifnot(nrow(a)==50, nrow(q)==50, !anyDuplicated(a$Student), !anyDuplicated(q$ID)); items <- paste0("Q",1:12); stopifnot(all(unlist(q[items]) %in% c(0,1))); stopifnot(all(q$Sub1==rowSums(q[items[1:4]])))
write.csv(data.frame(check=c("achievement_n","questionnaire_n","binary_items"),value=c(nrow(a),nrow(q),TRUE)),file.path(out_dir,"validation_report_R.csv"),row.names=FALSE)
